### ISSUE TITLE
Container instantly closes again

### ISSUE THREAD

**Issue by phrogg** [sdenel/docker-windscribe#1]
Hey, thanks for the container. For me the container closes itself as soon when I launch it.

```
Using OpenDNS as default DNS for security purposes
Starting Windscribe...
Starting windscribe ... OK
Please login to Windscribe. Don't have an account yet? The free offer includes 10Go/month. Go to: https://windscribe.com/?affid=06phaj3u (affiliated link)
Aborted!
Windscribe Username: Trying to connect (env variable CONNECTION_COUNTRY= you can set this env variable to a country abbreviation, ex 'RU')...
-Please login to use Windscribe
Enable firewall mode: You will not have any internet connectivity if you are not connected to Windscribe.�m
Please login to use Windscribe
Connected from XXXXXXXXXXX [XX, XXXXXX]
```

Where the Xs are IP Adress and stuff.

Do you have any Idea?

Thanks in advance 💯

**Comment by sdenel** [comment]
Hello @phrogg , did you launch it in interactive (-ti) mode?
This works for me:
`
docker run --cap-add=NET_ADMIN --device=/dev/net/tun -ti sdenel/docker-windscribe
`

**Comment by phrogg** [comment]
Thanks for the super quick answer! Right I missed that shame on me (/-\), thanks for pointing that out though!
